# Generated by Django 6.0.4 on 2026-04-16 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("intent", models.CharField(max_length=100)),
                (
                    "entities",
                    models.JSONField(
                        default=dict,
                        help_text="Stores extracted JSON data like amount, location, etc.",
                    ),
                ),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Stores the array of logical execution steps",
                    ),
                ),
                ("whatsapp_message", models.TextField(blank=True)),
                ("email_message", models.TextField(blank=True)),
                ("sms_message", models.CharField(blank=True, max_length=160)),
                ("assigned_team", models.CharField(max_length=100)),
            ],
        ),
    ]
