# Generated by Django 6.0.4 on 2026-04-18 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_task_reasoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="entities",
            field=models.JSONField(
                default=dict,
                help_text="Stores extracted JSON data like amount, location, recipient, etc.",
            ),
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="assistant.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
